/* game.c - plays the game */

/*
  int getmove(void) - gets opponent's move, 0:OK 1:QUIT
  int heurplay(void) - heuristic move Xheur 1:"MUST MOVE" 0:CONTINUE
  void searchplay(void) - search generated move Xsearch
  void learnplay(int t) - move Xlearn generated by recalling
  void killermove(void) - plays "MUST MOVE"
  void choose(void) - chooses between Xheur, Xsearch and Xlearn
  void putmove(void) - plays computer generated move
  int game(void) - invoked after the opening -1:DEFEAT 0:DRAW 1:WIN -2:BREAK
  int wholegame(int whomoves) - first entry into the game. Invokes opening,
                                then game. Return value same as for game.
*/

int getmove(void)
 {
  char s[80];
  char *phase;

  if(p0==-1) phase="[Ply]\0";
   else phase="[Reply]\0";

  l:
   printf("\n[Move %d] %s Enter your move... >", (n+1)/2, phase);
   (void)fgets(s, 80, stdin);
   if(s[0]=='q') return 1; /* quit */
   if(s[0]<'0' || s[0]>'4' || s[1]<'0' || s[1]>'4' ||
      s[2]<'0' || s[2]>'4' || s[3]<'0' || s[2]>'4' ||
      X[s[0]-'0'][s[1]-'0']!=-1 || X[s[2]-'0'][s[3]-'0']!=0) goto l;

  X[s[0]-'0'][s[1]-'0']=0;
  X[s[2]-'0'][s[3]-'0']=-1;
  return 0;
 } /* getmove */

int heurplay(void)
 {
  int t, e;
  position_t ptmp;

  if(p0!=0) { t=1; e=-1; }
   else { t=p; e=-p; } 

  copyposition(X, ptmp);

  if(thinking) printf("\nHeuristics: ");

  if(thinking) printf("m4 ");
  if(make4(t))
   {
    if(thinking) printf("\n");
    copyposition(X, Xheur);
    copyposition(ptmp, X);
    return 1;
   }

  if(thinking) printf("a4 ");
  if(avoid4(t, e))
   {
    if(thinking) printf("\n");
    copyposition(X, Xheur);
    copyposition(ptmp, X);
    return 1;
   }

  if(thinking) printf("md3 ");
  if(makedouble3(t, e))
   {
    if(thinking) printf("\n");
    copyposition(X, Xheur);
    copyposition(ptmp, X);
    return 0;
   }

  if(thinking) printf("mnd3 ");
  if(makenondefendable3(t, e))
   {
    if(thinking) printf("\n");
    copyposition(X, Xheur);
    copyposition(ptmp, X);
    return 0;
   }

  if(thinking) printf("ad3 ");
  if(avoiddouble3(t, e))
   {
    if(thinking) printf("\n");
    copyposition(X, Xheur);
    copyposition(ptmp, X);
    return 0;
   }

  if(thinking) printf("and3 ");
  if(avoidnondefendable3(t, e))
   {
    if(thinking) printf("\n");
    copyposition(X, Xheur);
    copyposition(ptmp, X);
    return 0;
   }

  if(thinking) printf("rnd \n");
  playrandom(t);
  copyposition(X, Xheur);
  copyposition(ptmp, X);
  return 0;
 } /* heurplay */

void searchplay(void)
 {
  int t, e;
  position_t ptmp;

  if(p0!=0) { t=1; e=-1; }
   else { t=p; e=-p; }

  copyposition(X, ptmp);

  if(thinking)
   {
    printf("Old eval:%d  ", eval(X, t, e));
    printf("Searching");
   }

  search(ptmp, t, e);

  if(thinking) printf("\n");
 } /* searchplay */

void learnplay(int t, int e)
 {
  position_t ptmp;

  if(!searchplaying)
   {
    develop1(ptmp, t); /* catch 22! if learning is OFF, how to find
                          position successors ?! we must develop... */
   }

  copyposition(X, ptmp);
  if(thinking) printf("Recalling");
  recall(t, e);

  if(thinking) printf("\n");
 } /* learnplay */

void killermove(void)
 {
  copyposition(Xheur, X);
  if(thinking) printf("(killer move occured)\n");
 } /* killermove */

void choose(void)
 {
  int t, e, evalsearch, evalheur, evallearn;

  if(p0!=0) { t=1; e=-1; }
   else { t=p; e=-p; }

  if(repeat>0)
   {
    switch(t)
     {
      case 1 :
       {
        heurplaying=autoh1; 
        searchplaying=autos1;
        learning=autol1;
        break;
       }
      case -1:
       {
        heurplaying=autoh2;
        searchplaying=autos2;
        learning=autol2;
        break;
       }
     }
   }

  if(thinking) printf("Choosing the best move.\n");
  
  if(heurplaying) evalheur=eval(Xheur, t, e);
   else evalheur=-MAXEVAL;

  if(searchplaying) evalsearch=eval(Xsearch, t, e);
   else evalsearch=-MAXEVAL;
  
  if(learning)
   {
    if(Xlearn[0][0]!=9) /* dirty, but... 9 at posiiton [0][0] means that
                           the learning module have not found a move */
     evallearn=eval(Xlearn, t, e);
    else
     evallearn=-MAXEVAL; /* didn't find any move in the memory */
   }
  else evallearn=-MAXEVAL;

  if(thinking)
   {
    printf("eval(heuristic)=");
    if(evalheur>-MAXEVAL) printf("%d ", evalheur);
     else printf("N/A ");

    printf("eval(search)=");
    if(evalsearch>-MAXEVAL) printf("%d ", evalsearch);
     else printf("N/A ");

    printf("eval(learn)=");
    if(learning)
     {
      if(evallearn>-MAXEVAL) printf("%d\n", evallearn);
       else printf("Not found\n");
     }
    else
     printf("N/A\n");
   }

  if(evallearn>-MAXEVAL)
   if(evallearn>=evalheur && evallearn>=evalsearch)
    {
     copyposition(Xlearn, X);
     if(thinking) printf("Playing the learned move.\n");
     return;
    }

  if(evalsearch>-MAXEVAL)
   {
    if(evalsearch>=evalheur && evalsearch>=evallearn)
     {
      copyposition(Xsearch, X);
      if(thinking) printf("Playing the search move.\n");
      return;
     }
   }

  if(evalheur>-MAXEVAL)
   {
    if(evalheur>=evallearn && evalheur>=evalsearch)
     {
      copyposition(Xheur, X);
      if(thinking) printf("Playing the heuristic move.\n");
      return;
     }
   }

  if(thinking) printf("Random move must be used...\n");
  playrandom(t);
  copyposition(X, Xheur);
 } /* choose */

void putmove(void)
 {
  int t, e;

  if(p0!=0) { t=1; e=-1; }
   else { t=p; e=-p; }

  if(repeat>0)
   {
    switch(t)
     {
      case 1 :
       {
        heurplaying=autoh1; 
        searchplaying=autos1;
        learning=autol1;
        break;
       }
      case -1:
       {
        heurplaying=autoh2;
        searchplaying=autos2;
        learning=autol2;
        break;
       }
     }
   }

  if(searchplaying || heurplaying || learning)
   {
    if(heurplaying)
     {
      if(heurplay()==1)
       { 
        killermove();
        return;
       }
     }
    if(searchplaying) searchplay();
    if(learning) learnplay(t, e);
   }
  else
   {
    if(thinking) printf("rnd \n");
    playrandom(t); /* it must exist at least one "engine" to play */    
    return;
   }

  choose();
 } /* putmove */

int game(void)
 {
  int ret, t, e;
  char s[80];
  char *phase;

  opengamememory_write();

  for(;;)
   {
    if(p0!=0) { t=1; e=-1; }
     else { t=p; e=-p; }

    if(p0==0)
     {
      /* did current player win ? */
      ret=four(X, t);
      if(ret)
       {
        closegamememory();
        return 1;
       }

      /* did opponent win ? */
      ret=four(X, e);
      if(ret)
       {
        closegamememory();
        return -1;
       }
     }
    else
     {
      ret=four(X, t);
      if(ret)
       {
        closegamememory();
        return 1;
       }

      ret=four(X, e);
      if(ret)
       {
        closegamememory();
        return -1;
       }
     }

    /* maybe it is a draw ? (chess like) */
    if(n>(9+4*DRAW-1) && p0==0)
     {
      if(isdraw(2) || isdraw(3) || isdraw(4))
       {
        closegamememory();
        return 0;
       }
     }

    if(n>(9+4*DRAW-1) && p0!=0)
     {
      if(isdraw(2) || isdraw(3) || isdraw(5))
       {
        if(p==1) /* only program can offer a draw */
         {
          if(offerdraw())
           {
            closegamememory();
            return 0;
           }
         }
       }
     }

    if(p0!=0)
     {
      if(p==1)
       {
        if(p0==1) phase="[Ply]\0";
         else phase="[Reply]\0";

        if(repeat==0)
         {
          printf("\n[Move %d] %s Thinking...\n", (n+1)/2, phase);
          if(!thinking) printf("\n");
         }
        putmove();
       }
      else
       {
        if(getmove()) return -2;
       }
     }
    else
     {
      if(pausing)
       {
        printf("\nPress ENTER for the next move... >");
        (void)fgets(s, 80, stdin);
        if(s[0]=='q')
         {
          closegamememory();
          return -2;
         }
       }

      if(p==1) phase="[Ply]\0";
       else phase="[Reply]\0";
      
      if(repeat==0)
       {
        printf("\n[Move %d] %s Thinking...", (n+1)/2, phase);
        if(!thinking) printf("\n");
       }
      putmove();
     }

    if(repeat==0)
     {
      if(p0==0) printposition(X, 1);
       else printposition(X, p0);
     }

    if(searchplaying && thinking)
     printf("\nNew eval:%d ", eval(X, t, e));

    saveposition(X, g); /* store current position into current game memory */
    nextinit();
   }
 } /* game */

int wholegame(int whomoves)
 {
  int ret;

  init(whomoves);

  if(p0==-1) printposition(X, p0);

  ret=opening();
  if(ret!=0) return ret; /* somebody won or stopped the opening */

  ret=game();
  return ret;
 } /* wholegame */

