/**
 * Created by mihailod, Mar 11, 2009, 9:55:04 PM
 *
 * Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n-1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n-1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
 */
public class Problem45 {
    private static int N = 100001;

    public static void main(final String[] args) {
        long start = System.currentTimeMillis();
        long time = System.currentTimeMillis();
        //for (long i=1; i<N; i++) {
        //    if (i % 10000 == 0) {
        //        System.out.println("i = " + i + " in " + (System.currentTimeMillis() - time) + "ms");
        //        time = System.currentTimeMillis();
        //    }
        //    long t = (i*(i+1))>>1;
            for (long j=1; j<N; j++) {
                long p = (j*(3*j - 1))>>1;
                //if (t < p || t > p) {
                //    continue;
                //} else {
                //    System.out.println("candidate " + p + " t = " + i + " p = " + j + "...");
                //}
                for (long k=1; k<N; k++) {
                    long h = k *(2*k - 1);
                    if (h > p) {
                        break;
                    }
                    if (p == h /*&& t == p*/) {
                        System.out.print("GOTCHA " + p);
                        //System.out.print(" t = " + i);
                        System.out.print(" p = " + j);
                        System.out.println(" h = " + k);
                        if(p > 40755) {
                            System.out.println("It took: " + (System.currentTimeMillis() - start) + "ms" );
                            System.exit(0);
                        }
                    }
                }
            }
        //}

    }
}
