import java.util.Hashtable;

/**
 * Created by mihailod, Mar 11, 2009, 11:30:13 PM
 *
 * Pentagonal numbers are generated by the formula, Pn=n(3n-1)/2.
 *  The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8.
 However, their difference, 70 - 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk,
 for which their sum and difference is pentagonal
 and D = |Pk - Pj| is minimised; what is the value of D?
 */
public class Problem44 {
    static long pents[] = new long[5000];
    private static final long N = 5000;
    static Hashtable ht = new Hashtable();

    public static void main(final String[] args) {
        long start = System.currentTimeMillis();
        for (int i=0; i<N; i++) {
            long ii = (long)i;
            long p = (ii*(3*ii - 1))>>1;
            pents[i] = p;
            if (p > 0) {
                ht.put(p, p);
            }
        }
        for (int i=1; i<pents.length; i++) {
            /*if (i % 10 == 0) {
                System.out.println("i = " + i);
            }*/
            long p1 = pents[i];
            for (int j=i; j<pents.length; j++) {
                long p2 = pents[j];
                long sum = p1 + p2;
                long diff = p1 > p2 ? p1 - p2 : p2 - p1;
                if (ht.get(diff) != null && ht.get(sum) != null) {
                    System.out.print("p1 = " + p1);
                    System.out.println(" p2 = " + p2);
                    System.out.println("diff = " + diff);
                    System.out.println("done in " + (System.currentTimeMillis() - start) + "ms");
                }
            }
        }
    }
}
