// Word Finder for Letter Puzzles word list builder — Node port of lps.Preprocessor (Mihailo Despotovic, 2003)
//
// Usage: node preprocess.mjs <inputFile> <minLetters> <maxLetters>
// Reads a dictionary with one '<b>word</b>' per line and writes words.js,
// which lps.html loads with a plain <script> tag (so it also works from file://).

import { readFileSync, writeFileSync, existsSync } from "node:fs";

const PROGRESS_TICK = 20000;

function usage() {
    console.log("Preprocessor will create the words.js file");
    console.log("Usage: node preprocess.mjs <inputFile> <minLetters> <maxLetters>");
    console.log("File should exist, min>=1, max<=12.");
    process.exit(1);
}

const args = process.argv.slice(2);
if (args.length !== 3) usage();
const [file, minArg, maxArg] = args;
if (!existsSync(file)) {
    console.log("Bad arguments:\nFile doesn't exist!");
    usage();
}
const min = Number(minArg);
const max = Number(maxArg);
if (!Number.isInteger(min) || !Number.isInteger(max) || min < 1 || max > 12) {
    console.log("Bad arguments:\nBad min/max number.");
    usage();
}

// This is highly data dependent!!! Expects one '<b>word</b>' combination per line
function getWord(line) {
    const s = line.toLowerCase();
    const start = s.indexOf("<b>");
    const end = s.indexOf("</b>");
    if (start < 0 || end < 0) return null;
    const word = s.substring(start + 3, end);
    if (/['\- \/".()]/.test(word)) return null;
    return word.trim();
}

let totalWords = 0, shorter = 0, longer = 0, badLines = 0;
const words = new Set(); // the dictionary lists a word once per definition; keep the first

for (const line of readFileSync(file, "latin1").split(/\r?\n/)) {
    const word = getWord(line);
    if (word === null) { badLines++; continue; }
    totalWords++;
    if (totalWords % PROGRESS_TICK === 0) console.log(totalWords + " processed so far...");
    if (word.length > max) longer++;
    else if (word.length < min) shorter++;
    else if (!/^[a-z]+$/.test(word)) badLines++;
    else words.add(word);
}

writeFileSync("words.js",
    "// Generated by preprocess.mjs — do not edit\n" +
    "const WORDS = \"" + [...words].join(" ") + "\".split(\" \");\n");

console.log("Done!");
console.log("Bad lines " + badLines);
console.log("Total words " + totalWords);
console.log("Words shorter than " + min + ": " + shorter);
console.log("Words longer than " + max + ": " + longer);
console.log("Final number of OK words " + (totalWords - (shorter + longer)));
console.log("Unique words written to words.js: " + words.size);
